services:
  db:
    container_name: db
    image: postgres:11
    ports:
      - 6432:5432
    networks:
      - tjnet
    environment:
      - POSTGRES_DB=postgres_demo
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  dbgate:
    container_name: dbgate
    image: dbgate/dbgate:latest
    restart: always
    networks:
      - tjnet
    ports:
      - '2222:3000'
networks:
  tjnet:
    external: true